--INSERT BOOKS
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'A Tale of Two Cities', '1859-01-01', 'Charles Dickens', 'HISTORICAL_FICTION');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'The Little Prince', '1943-01-01', 'Antoine de Saint-Exupery', 'NOVELLA');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'Harry Potter and the Philosopher''s Stone', '1997-01-01', 'J. K. Rowling', 'FANTASY');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'And Then There Were None', '1939-01-01', 'Agatha Christie', 'MYSTERY');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'The Hobbit', '1937-01-01', 'J. R. R. Tolkien', 'FANTASY');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'The Lion, the Witch and the Wardrobe', '1950-01-01', 'C. S. Lewis', 'FANTASY');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'She: A History of Adventure', '1887-01-01', 'H. Rider Haggard', 'ADVENTURE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'Vardi Wala Gunda', '1992-01-01', 'Ved Prakash Sharma', 'DETECTIVE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'The Da Vinci Code', '2003-01-01', 'Dan Brown', 'MYSTERY');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('BOOK', 'Harry Potter and the Chamber of Secrets', '1998-01-01', 'J. K. Rowling', 'FANTASY');
--INSERT MAGAZINES
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Food Network Magazine', '2022-01-10', '', 'COOKING');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Food Network Magazine', '2022-02-10', '', 'COOKING');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Food Network Magazine', '2022-03-10', '', 'COOKING');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Food Network Magazine', '2022-04-10', '', 'COOKING');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Food Network Magazine', '2022-05-10', '', 'COOKING');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Family Handyman', '2022-01-15', '', 'HOUSE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Family Handyman', '2022-02-15', '', 'HOUSE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Family Handyman', '2022-03-15', '', 'HOUSE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Family Handyman', '2022-04-15', '', 'HOUSE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'Family Handyman', '2022-05-15', '', 'HOUSE');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'National Geographic Little Kids', '2022-01-25', '', 'CHILDREN');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'National Geographic Little Kids', '2022-02-25', '', 'CHILDREN');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'National Geographic Little Kids', '2022-03-25', '', 'CHILDREN');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'National Geographic Little Kids', '2022-04-25', '', 'CHILDREN');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('MAGAZINE', 'National Geographic Little Kids', '2022-05-25', '', 'CHILDREN');
--INSERT NEWSPAPERS
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Yomiuri Shimbun', '2022-01-03', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Yomiuri Shimbun', '2022-01-10', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Yomiuri Shimbun', '2022-01-17', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Yomiuri Shimbun', '2022-01-24', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Yomiuri Shimbun', '2022-01-31', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Jagran', '2022-01-04', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Jagran', '2022-01-11', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Jagran', '2022-01-18', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Jagran', '2022-01-25', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Jagran', '2022-02-01', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Bhaskar', '2022-01-05', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Bhaskar', '2022-01-12', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Bhaskar', '2022-01-19', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Bhaskar', '2022-01-26', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Dainik Bhaskar', '2022-02-02', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Reference News', '2022-01-06', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Reference News', '2022-01-13', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Reference News', '2022-01-20', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Reference News', '2022-01-27', '', 'NEWS');
INSERT INTO PRINT_PRODUCTS (type, name, date_published, author, genre) VALUES ('NEWSPAPER', 'Reference News', '2022-02-03', '', 'NEWS');